<?xml version="1.0"?>
<package format="3">
  <name>bfmc_isaac_visual_slam</name>
  <version>0.1.0</version>
  <description>UniPD DriveOps launch wrapper for NVIDIA Isaac ROS Visual SLAM.</description>
  <maintainer email="driveops@unipd.it">UniPD DriveOps</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclcpp_components</exec_depend>
  <exec_depend>isaac_ros_visual_slam</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
